##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.11.2] date: [Sat Jan 13 22:12:15 CST 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = AliosThingsDeveloper


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
main/audio.c \
main/gc0329.c \
main/irda.c \
main/isd9160.c \
main/main.c \
main/soc_init.c \
main/st7789.c \
main/stm32l4xx_hal_msp.c \
main/stm32l4xx_it.c \
main/system_stm32l4xx.c \
main/APP/atdemo.c \
main/APP/camera_demo.c \
main/APP/crc16.c \
main/APP/id2_client_demo.c \
main/hal/hal_gpio_stm32l4.c \
main/hal/hal_i2c_stm32l4.c \
main/hal/hal_sd_stm32l4.c \
main/hal/hal_smartcard_stm32l4.c \
main/hal/hal_uart_stm32l4.c \
aos/soc_impl.c \
aos/trace_impl.c \
armv7m/armcc/m4/port_c.c \
Config/GUIConf.c \
Config/LCDConf_FlexColor_Template.c \
framework/uData/abs_data_model.c \
framework/uData/calibrated_example_algo.c \
framework/uData/service_mgr.c \
framework/uData/uData_interface.c \
framework/uData/uData_main.c \
framework/common/main.c \
framework/common/version.c \
GUI/core/GUI_init.c \
GUI/STemWin/OS/GUI_X_rhino.c \
GUIDEMO/GUIDEMO.c \
GUIDEMO/GUIDEMO_BarGraph.c \
GUIDEMO/GUIDEMO_ColorBar.c \
GUIDEMO/GUIDEMO_Conf.c \
GUIDEMO/GUIDEMO_Graph.c \
GUIDEMO/GUIDEMO_Intro.c \
GUIDEMO/GUIDEMO_Resource.c \
GUIDEMO/GUIDEMO_Start.c \
GUIDEMO/GUIDEMO_TransparentDialog.c \
GUIDEMO/GUIDEMO_Uncalssified.c \
sensor/drv/drv_acc_gyro_temp_st_lsm6dsl.c \
sensor/drv/drv_als_ps_liteon_ltr553.c \
sensor/drv/drv_baro_bosch_bmp280.c \
sensor/drv/drv_mag_temp_memsic_mmc3680kj.c \
sensor/drv/drv_temp_humi_sensirion_shtc1.c \
sensor/hal/sensor_drv_api.c \
sensor/hal/sensor_hal.c \
utility/base64.c \
utility/CheckSumUtils.c \
utility/crc.c \
utility/digest_algorithm.c \
utility/hmac.c \
utility/log.c \
utility/md5.c \
kernel/aos/aos_rhino.c \
kernel/fatfs/diskio.c \
kernel/fatfs/fatfs.c \
kernel/fatfs/ff.c \
kernel/fatfs/ffunicode.c \
kernel/init/aos_init.c \
kernel/rhino/k_buf_queue.c \
kernel/rhino/k_dyn_mem_proc.c \
kernel/rhino/k_err.c \
kernel/rhino/k_event.c \
kernel/rhino/k_fifo.c \
kernel/rhino/k_idle.c \
kernel/rhino/k_mm.c \
kernel/rhino/k_mm_blk.c \
kernel/rhino/k_mm_debug.c \
kernel/rhino/k_mutex.c \
kernel/rhino/k_obj.c \
kernel/rhino/k_obj_set.c \
kernel/rhino/k_pend.c \
kernel/rhino/k_queue.c \
kernel/rhino/k_ringbuf.c \
kernel/rhino/k_sched.c \
kernel/rhino/k_sem.c \
kernel/rhino/k_stats.c \
kernel/rhino/k_sys.c \
kernel/rhino/k_task.c \
kernel/rhino/k_task_sem.c \
kernel/rhino/k_tick.c \
kernel/rhino/k_time.c \
kernel/rhino/k_timer.c \
kernel/rhino/k_trace.c \
kernel/rhino/k_workqueue.c \
kernel/vfs/device.c \
kernel/vfs/vfs.c \
kernel/vfs/vfs_inode.c \
kernel/vfs/vfs_register.c \
kernel/yloop/local_event.c \
kernel/yloop/yloop.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_can.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_comp.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cryp.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cryp_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dac.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dac_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dcmi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dfsdm.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dfsdm_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma2d.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dsi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_firewall.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gfxmmu.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_hash.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_hash_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_hcd.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_irda.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_iwdg.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_lcd.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_lptim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_ltdc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_ltdc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_nand.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_nor.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_opamp.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_opamp_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_ospi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_qspi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rng.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sai.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sai_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sd.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sd_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_smartcard.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_smartcard_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_smbus.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sram.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_swpmi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tsc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_usart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_usart_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_wwdg.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_adc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_comp.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_crc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_crs.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_dac.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_dma.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_dma2d.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_exti.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_fmc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_gpio.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_i2c.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_lptim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_lpuart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_opamp.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_pwr.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_rcc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_rng.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_rtc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_sdmmc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_spi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_swpmi.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_tim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usb.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_utils.c

# ASM sources
ASM_SOURCES =  \
Startup/startup_stm32l496xx.s \
rmv7m/gcc/m4/port_c.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L496xx \
-DSYSINFO_OS_VERSION=\"APP-1.0.0\" -DSYSINFO_PRODUCT_MODEL=\"ALI_AOS_STM32L496AGIx\" \
-DSYSINFO_DEVICE_NAME=\"STM32LL496AGIx\" -DSYSINFO_KERNEL_VERSION=\"AOS-R-1.1.2\" \
-DSYSINFO_APP_VERSION=\"APP-1.0.0\" -DSTDIO_UART=0 -DCONFIG_NO_TCPIP -DRHINO_CONFIG_TICK_TASK=0 \
-DCONFIG_AOS_KV_MULTIPTN_MODE \
-DCONFIG_AOS_KV_PTN=6 \
-DCONFIG_AOS_KV_SECOND_PTN=7 \
-DCONFIG_AOS_KV_PTN_SIZE=4096 \
-DCONFIG_AOS_KV_BUFFER_SIZE=8192 \
-D__BSD_VISIBLE \
-DRHINO_CONFIG_TICK_TASK=0 \
-DAOS_SENSOR \
-DAOS_VFS \
-DAOS_FRAMEWORK_COMMON \
-DAOS_UDATA \
-DCONFIG_AOS_FATFS_SUPPORT_MMC

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Iutility/inc \
-Isensor/include \
-Imain/include \
-Imain/hal/inc \
-Imain/APP/inc \
-Ikernel/inc \
-Ikernel/rhino/include \
-IGUI/STemWin/inc \
-IGUI/core/include \
-Iframework/include \
-IDrivers/STM32L4xx_HAL_Driver/Inc \
-IDrivers/CMSIS/Device/ST/STM32L4xx/Include \
-IConfig/inc \
-Iarmv7m/gcc/m4 \
-Iinclude/aos/internal \
-Iinclude/hal/soc \
-Iinclude/aos \
-Iinclude/hal \
-Iutility/libc/compilers/armlibc \
-Iutility/libc/compilers/armlibc/sys \
-Iutility/libc/compilers/armlibc/RVMDK \
-IDrivers/STM32L4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = Core/Startup/STM32L496VGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***